import Head from "next/head";
import useStyles from "@/components/Generator/Generator.styles";
import { Text, Title, TextInput, Button } from "@mantine/core";
import useGenerateIA from "@/lib/hook/useGenerateIA";

export default function Banner() {
  const { classes } = useStyles();
  const { data } = useGenerateIA();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.wrapper}>
        <div className={classes.body}>
          <Title className={classes.title}>Wait a minute...</Title>
          <Text weight={500} size="lg" mb={5}>
            Subscribe to our newsletter!
          </Text>
          <Text size="sm" color="dimmed">
            {data[0]?.text ?? "NO data"}
          </Text>

          <div className={classes.controls}>
            <TextInput
              placeholder="Your email"
              classNames={{
                input: classes.input,
                root: classes.inputWrapper,
              }}
            />
            <Button className={classes.control}>Subscribe</Button>
          </div>
        </div>
      </main>
    </>
  );
}
