import Head from "next/head";
import useStyles from "@/components/Generator/Generator.styles";
import { Skeleton, Stack, Text, Title } from "@mantine/core";
import useGenerateIA from "@/lib/hook/useGenerateIA";
import { useState } from "react";
import TypeDiets from "./TypesDiets";

export default function Banner() {
  const [text] = useState("lose weight");
  const { classes } = useStyles();
  const { data, loading } = useGenerateIA({ text });
  console.log(loading);
  return (
    <>
      <Head>
        <title>Generate Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.wrapper}>
        <div className={classes.body}>
          {loading ? (
            <Stack sx={{ width: "100%" }}>
              <Title className={classes.title}>Wait a minute...</Title>
              <Skeleton height={8} radius="xl" />
              <Skeleton height={8} radius="xl" />
              <Skeleton height={8} radius="xl" />
            </Stack>
          ) : (
            <>
              <Title className={classes.title}>IA Response!</Title>
              <Text size="sm" color="dimmed">
                {data[0]?.text ?? "NO data"}
              </Text>
            </>
          )}
        </div>
      </main>
      <TypeDiets />
    </>
  );
}
